### ISSUE TITLE
Decrypt first block (supply IV)

### ISSUE THREAD

**Issue by luisfontes19** [KishanBagaria/padding-oracle-attacker#6]
Hey,

Do you plan to add support to supply the IV as a param to decrypt the first block?

**Comment by KishanBagaria** [comment]
It's already supported. Simply prefix the ciphertext with the IV.

So if your ciphertext is `BBBBCCCC` and IV is `AAAA`, supply this as your ciphertext: `AAAABBBBCCCC`

**Comment by luisfontes19** [comment]
ooh makes sense.

Great, thank you
