### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ashraful1980** [KishanBagaria/padding-oracle-attacker#8]
I have tried many time to installation "padding-oracle-attacker" but unable to installation. It is find Error Massage as following attached. Could you please advice how to installation for this software.... I need your help..
![Error_Massage](https://user-images.githubusercontent.com/52574658/89985387-cd900c80-dc9c-11ea-969b-cf026c22979b.jpg)

**Comment by KishanBagaria** [comment]
Looks like some error with permissions on your environment.

You can try running `npx padding-oracle-attacker ...`.

Another alternative: run `npm run build` and `node dist/cli ...`

**Comment by ashraful1980** [comment]
I have install it; but no terminal created as "poattack" please help me...
![terminal](https://user-images.githubusercontent.com/52574658/89991085-21065880-dca5-11ea-8771-8ea31128bdc7.jpg)

**Comment by ashraful1980** [comment]
![terminal](https://user-images.githubusercontent.com/52574658/89991596-ddf8b500-dca5-11ea-9082-c6daf9825e92.jpg)

**Comment by KishanBagaria** [comment]
What command did you use that printed the usage instructions? Simply use that again and append the args. If you're running `X` then run `X analyze ...` or `X decrypt ...`

**Comment by ashraful1980** [comment]
Dear Sir,
Have a nice day and hope you are fine.

Finally i have installed correctly to your valuable software; it is fantastic encrypt & decrypt program.
Attached result:
![result](https://user-images.githubusercontent.com/52574658/103983029-c9660d80-51ae-11eb-8524-c86229836653.jpg)

---plaintext printable bytes in utf8---
Follow the white rabbit ....


Also i have tried sample encrypted password protected key; it is unable to result yet.
Attached result:
![nagetive](https://user-images.githubusercontent.com/52574658/103983005-bc491e80-51ae-11eb-9f65-1384ba04c8fc.jpg)

---plaintext printable bytes in utf8---
~�]>�..�䀨�ޛn!��2a.G�c.bx��&�L
The plaintext correct string is: Aa1@ 
Could you please give me proper guideline; how it is crack easily....

I am waiting for your valuable response....


Thanks & Best Regards,
Md. Ashraful Alam

**Comment by KishanBagaria** [comment]
I recommend using something like PadBuster first to understand padding oracle attacks: https://github.com/AonCyberLabs/PadBuster

Lots of videos on YouTube to demonstrate usage.
